openapi: 3.0.0
info:
  title: 'GnuBoard5 API Test Documentation'
  description: 'Swagger OpenApi description Test'
  contact:
    email: admin@admin.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
paths:
  /api/v1/token:
    post:
      tags:
        - 인증
      summary: 'Access/Refresh Token 발급'
      description: 'Access Token & Refresh Token을 발급합니다.'
      operationId: 8e03e8c7922c70f6e5fbdad4202d66cc
      responses:
        '200':
          description: ''
  /api/v1/token/refresh:
    post:
      tags:
        - 인증
      summary: 'Refresh Token 재발급'
      description: 'Refresh Token을 이용하여 Access Token을 재발급합니다.'
      operationId: f1f53bb425188289820fcda4ab79ac1b
      responses:
        '200':
          description: ''
  /api/v1/config/html:
    get:
      tags:
        - 환경설정
      summary: 'HTML 설정 조회'
      description: 'HTML을 구성하는데 필요한 설정 정보를 조회합니다.'
      operationId: 5d1063d78abd2d407baa4a7d34a0abd0
      responses:
        '200':
          description: 'Successful Response'
          content:
            application/json:
              schema:
                properties:
                  cf_title: { description: '사이트 제목', type: string }
                  cf_add_meta: { description: '추가 메타태그', type: string }
                  cf_add_script: { description: '추가 스크립트', type: string }
                  cf_analytics: { description: 분석코드, type: string }
                type: object
              examples:
                result:
                  value: { cf_title: string, cf_add_meta: string, cf_add_script: string, cf_analytics: string }
        '500':
          description: '서버 오류'
  /api/v1/config/policy:
    get:
      tags:
        - 환경설정
        - 회원
      summary: '회원가입약관 조회'
      description: '회원가입 약관을 조회합니다.<br> - 회원가입 약관 <br> - 개인정보 수집 및 허용 약관'
      operationId: 07c46bfd244961b88286addf0c64d58e
      responses:
        '200':
          description: ''
  /api/v1/config/member:
    get:
      tags:
        - 환경설정
        - 회원
      summary: '회원가입 설정 조회'
      description: '회원가입에 필요한 환경설정 정보를 조회합니다.'
      operationId: 259da4e5e14ed20e7ed5c35132b7f139
      responses:
        '200':
          description: ''
  /api/v1/config/memo:
    get:
      tags:
        - 환경설정
      summary: '쪽지 발송 소진 포인트 조회'
      description: '쪽지 발송 시, 1건당 소모되는 포인트 설정 정보를 조회합니다.'
      operationId: 8c2614e4159a0f8ad89fa3cfb4d25b9f
      responses:
        '200':
          description: ''
  /api/v1/config/board:
    get:
      tags:
        - 환경설정
      summary: '게시판 설정 조회'
      description: '게시판에 사용되는 설정 정보를 조회합니다.'
      operationId: 8c900e31ff563290d83040baa6c38c09
      responses:
        '200':
          description: ''
  /api/v1/members:
    post:
      tags:
        - 회원
      summary: 회원가입
      description: '회원가입을 진행합니다.'
      operationId: 0e80e12223f56d817ee88232f74d50c4
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                mb_id:
                  description: 아이디
                  type: string
                  example: test
                mb_password:
                  description: 비밀번호
                  type: string
                  example: test1234
                mb_password_re:
                  description: '비밀번호 확인'
                  type: string
                  example: test1234
                mb_name:
                  description: 이름
                  type: string
                  example: 홍길동
                mb_nick:
                  description: 닉네임
                  type: string
                  example: 홍길동
                mb_email:
                  description: 이메일
                  type: string
                  example: ''
                mb_recommend:
                  description: 추천인
                  type: string
                  example: ''
                mb_hp:
                  description: '휴대폰 번호'
                  type: string
                  example: ''
                mb_zip:
                  description: 우편번호
                  type: string
                  example: ''
              type: object
      responses:
        '200':
          description: ''
  '/api/v1/members/{mb_id}/email-certification/change':
    put:
      tags:
        - 회원
      summary: '인증 이메일 변경'
      description: '메일인증을 처리하지 않은 회원의 메일을 변경하고 인증메일을 재전송합니다.'
      operationId: d41a3675dfd37a03e30f6b226b8c42a2
      parameters:
        -
          name: mb_id
          in: path
          description: '회원 ID'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  description: '변경 이메일'
                  type: string
                password:
                  description: '회원 비밀번호'
                  type: string
              type: object
      responses:
        '200':
          description: ''
  /api/v1/members/me:
    get:
      tags:
        - 회원
      summary: '현재 로그인 회원정보 조회'
      description: 'JWT 토큰을 통해 인증된 회원 정보를 조회합니다.'
      operationId: c36d9f57d1576b356a131deab6278550
  '/api/v1/members/{mb_id}':
    get:
      tags:
        - 회원
      summary: '회원정보 조회'
      description: '회원 정보를 조회합니다.'
      operationId: 341380afdb3856663bba53c8148842ce
      parameters:
        -
          name: mb_id
          in: path
          description: '회원 ID'
          required: true
          schema:
            type: string
  /api/v1/member:
    put:
      tags:
        - 회원
      summary: '회원정보 수정'
      description: 'JWT 토큰을 통해 인증된 회원 정보를 수정합니다.'
      operationId: e7a371b8b809ea949af9400f8bd88efa
    delete:
      tags:
        - 회원
      summary: 회원탈퇴
      description: 'JWT 토큰을 통해 인증된 회원을 탈퇴합니다.'
      operationId: 7478967c7d59be68a9d55fa1468ffe17
      responses:
        '200':
          description: ''
  /api/v1/member/images:
    put:
      tags:
        - 회원
      summary: '회원 아이콘&이미지 수정'
      description: 'JWT 토큰을 통해 인증된 회원의 아이콘 & 이미지를 수정합니다.'
      operationId: bdb6532e2ad7753e50a631f2f26efb85
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                mb_img:
                  description: '회원 이미지'
                  type: string($binary)
                mb_icon:
                  description: '회원 아이콘'
                  type: string($binary)
                del_mb_img:
                  description: '회원 이미지 삭제여부'
                  type: integer
                del_mb_icon:
                  description: '회원 아이콘 삭제여부'
                  type: integer
              type: object
      responses:
        '200':
          description: ''
tags:
  -
    name: 환경설정
    description: '기능별 환경설정정보 API'
  -
    name: 인증
    description: '인증 API'
  -
    name: 회원
    description: '회원 API'
